// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnhtvedgnqzecdlihghd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduaHR2ZWRnbnF6ZWNkbGloZ2hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5MDEwODEsImV4cCI6MjA3OTQ3NzA4MX0.SKxNMLqEJsgfE7cJMn0h63KdnoGROoYUo2pL6ty7yPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});